import type { BlogPost, Location } from '@/lib/types';

export const placeholderBlogPosts: BlogPost[] = [
  {
    id: '1',
    slug: 'tendencias-bano-2024',
    title: 'Principales Tendencias de Baño para 2024',
    date: '2024-07-15',
    excerpt: 'Descubre los últimos estilos e innovaciones en diseño de baños para el próximo año.',
    imageUrl: 'https://placehold.co/800x500.png',
    content: '<p>El mundo del diseño de baños está en constante evolución. En 2024, estamos viendo un cambio hacia...</p><p>Se exploran materiales naturales, diseños minimalistas y tecnología integrada para crear espacios que son tanto funcionales como relajantes.</p>',
    author: 'Juana Pérez',
    tags: ['tendencias', 'diseño', 'baño'],
    dataAiHint: 'bathroom design',
  },
  {
    id: '2',
    slug: 'creando-un-refugio-spa-en-casa',
    title: 'Creando un Refugio Tipo Spa en Casa',
    date: '2024-06-28',
    excerpt: 'Transforma tu baño en un santuario personal con estos consejos y trucos.',
    imageUrl: 'https://placehold.co/800x500.png',
    content: '<p>Tu baño puede ser más que un espacio funcional. Con algunos cambios clave, puedes crear un ambiente de spa que promueva la relajación y el bienestar. Considera la iluminación, los textiles y los aromas.</p>',
    author: 'Juan García',
    tags: ['spa', 'lujo', 'mejoras hogar'],
    dataAiHint: 'spa bathroom',
  },
  {
    id: '3',
    slug: 'opciones-sostenibles-bano',
    title: 'Opciones Sostenibles para un Baño Ecológico',
    date: '2024-05-10',
    excerpt: 'Aprende cómo hacer tu baño más verde con prácticas y materiales sostenibles.',
    imageUrl: 'https://placehold.co/800x500.png',
    content: '<p>La sostenibilidad es más importante que nunca. Así es como puedes tomar decisiones ecológicas para tu baño, desde la elección de materiales hasta el ahorro de agua y energía.</p>',
    author: 'Alicia Verde',
    tags: ['sostenibilidad', 'ecológico', 'diseño verde'],
    dataAiHint: 'eco bathroom',
  },
];

export const placeholderLocations: Location[] = [
  {
    id: '1',
    name: 'Showroom Vivenza Centro',
    address: 'Calle Principal 123, Cualquier Ciudad, País 12345',
    phone: '+34 900 123 456',
    imageUrl: 'https://placehold.co/600x400.png',
    lat: 40.416775,
    lng: -3.703790,
    openingHours: 'Lun-Sáb: 10 AM - 7 PM, Dom: 12 PM - 5 PM',
    dataAiHint: 'modern showroom',
  },
  {
    id: '2',
    name: 'Galería Vivenza Norte',
    address: 'Avenida del Roble 456, Otra Villa, País 67890',
    phone: '+34 900 987 654',
    imageUrl: 'https://placehold.co/600x400.png',
    lat: 40.516775,
    lng: -3.803790,
    openingHours: 'Lun-Vie: 9 AM - 6 PM, Sáb: 10 AM - 4 PM',
    dataAiHint: 'store interior',
  },
];
